[build]
  base = "frontend/"
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_API_URL = "https://slooze-assignment.onrender.com/graphql"

[[redirects]]
  from = "/api/*"
  to = "https://slooze-assignment.onrender.com/api/:splat"
  status = 200
